development:
   adapter: h2
   connectionpool: dhcp
   protocol: jdbc
   database: slipp-user
   username: sa
   
test:
   adapter: mysql
   connectionpool: dhcp
   protocol: jdbc
   host: localhost
   port: 3306
   database: slipp_user_test
   username: root
   
production:
   adapter: mysql
   connectionpool: c3p0  
   protocol: jdbc
   host: localhost
   port: 3306
   database: slipp_user
   username: root

